datamodule:
  name: CpClassifierDataModule
  config:
    dataset_dir: </path/to/chameleon/dfs/dataset>
    batch_size: 128
    num_workers: 8
    labels:
      0: 0 # aes other
      1: 1 # aes first
      2: 2 # noise
